- name: Docker Login
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Build and push backend image
  uses: docker/build-push-action@v4
  with:
    context: .
    file: infra/docker/Dockerfile.backend
    push: true
    tags: your-docker-registry/indoblockforge-backend:latest

- name: Build and push frontend image
  uses: docker/build-push-action@v4
  with:
    context: .
    file: infra/docker/Dockerfile.frontend
    push: true
    tags: your-docker-registry/indoblockforge-frontend:latest
